
import type { Metadata } from 'next';
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/app-sidebar"
import { Header } from '@/components/header';
import ThemeToggle from '@/components/theme-toggle';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <SidebarProvider defaultOpen={false}>
        <AppSidebar />
          <div className='flex flex-col h-screen w-full'>
          <Header />
          {children}
          </div>
      </SidebarProvider>
    </>
  );
}
