
import type { Metadata } from 'next';
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/app-sidebar"
import { Header } from '@/components/header';
import ThemeToggle from '@/components/theme-toggle';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <main>
      <SidebarProvider defaultOpen={false}>
      <AppSidebar />
      {/* <SidebarTrigger /> */}
      <div className='flex flex-col h-screen'>
       {/* ===== Top Heading ===== */}
            <Header className='flex justify-between w-full'>
              {/* <Search /> */}
              <div className='ml-auto flex items-center gap-4'>
                <ThemeToggle />
                {/* <ProfileDropdown /> */}
              </div>
            </Header>
        {children}
        </div>
      </SidebarProvider>
        </main>
  );
}
